language: node_js
node_js:
  - "8.12"
sudo: false
cache:
  directories:
    - node_modules
before_install:
  # Configure npm
  - npm config set shrinkwrap false
  - npm rm --silent --save-dev connect-redis
  - npm install lint
  - if [[ -d node_modules ]]; then
      npm prune
      npm rebuild
    fi
script:
  - npm run test-ci
  - npm run lint
after_script:
  - npm install --save-dev coveralls@2.10.0
    coveralls < ./coverage/lcov.info
