language: node_js
node_js:
  - "8.12"
sudo: false
cache:
  directories:
    - node_modules
before_install:
  - npm install
  - npm install eslint
  - npm prune
  - npm rebuild
script:
  - npm run eslint
  - node ./app.js ./test/test-1.ged | diff ./test/test-1.pass -
  - echo "Done"
