language: node_js
node_js:
  - "8.12"
sudo: false
cache:
  directories:
    - node_modules
before_install:
  - npm config set shrinkwrap false
  - npm rm --silent --save-dev connect-redis
  - npm install eslint
  - if [[ -d node_modules ]]; then
      npm prune
      npm rebuild
    fi
script:
  - npm run eslint
